### ISSUE TITLE
[polaris] upgrade version in chart

### ISSUE THREAD

**Issue by davidkarlsen** [FairwindsOps/charts#111]
There seems to be 0.3.x versions available - shouldn't the chart be updated on releases?

**Comment by bambash** [comment]
hi @davidkarlsen - new chart versions are published automatically. I was able to see the new polaris chart after running `helm repo update`. Is your local repository index up to date?

```
$ helm search polaris
NAME                      	CHART VERSION	APP VERSION	DESCRIPTION                                             
fairwinds/polaris         	0.4.0        	0.2        	Validation of best practices in your Kubernetes clusters```

**Comment by davidkarlsen** [comment]
Yes, the chart is updated, but still tag is: 0.2: https://github.com/FairwindsOps/charts/blob/master/stable/polaris/values.yaml#L53, while latest image avail is 0.3.1:  https://quay.io/repository/reactiveops/polaris?tab=tags

**Comment by bambash** [comment]
Ah, yes - I see. There are currently two open PRs that will bump the application version. The maintainers of Polaris have some chart modifications that need to happen before the image tag can be bumped.

**Comment by davidkarlsen** [comment]
Doh - I should have noticed.
Linking:
https://github.com/FairwindsOps/charts/pull/106
https://github.com/FairwindsOps/charts/pull/101

**Comment by endzyme** [comment]
Thanks for the ask @davidkarlsen! We'll be checking things over and hope to be releasing 0.4.0 in the next day or two!

:) Sorry for the delay!
