### ISSUE TITLE
capsize has outdated specs

### ISSUE THREAD

**Issue by bbensky** [FairwindsOps/charts#222]
**Describe the bug**
Installing Capsize results in an error.

**To Reproduce**
1. run `helm install capsize fairwinds-incubator/capsize`

**Expected behavior**
The chart installs successfully

**CLI Output**
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CronJob.spec.jobTemplate.spec.template.spec): unknown field "metadata" in io.k8s.api.core.v1.PodSpec, ValidationError(CronJob.spec): unknown field "restartPolicy" in io.k8s.api.batch.v1beta1.CronJobSpec]
```

**Environment (please complete the following information):**
 - Helm Version: 3.0.0
 - Kubernetes Version 1.15.7

**Comment by sudermanjr** [comment]
This has been fixed.
