### ISSUE TITLE
[insights-agent] [goldilocks] Support windows nodes

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/charts#262]
**Is your feature request related to a problem? Please describe.**
The VPA install process relies on `ci-images`, which struggles on Windows nodes. We've seen reports of the following error:
```
 Warning Failed         16m                  kubelet, akswpool100000h Failed to pull image "quay.io/reactiveops/ci-images:v9-alpine": rpc error: code = Unknown desc = failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?
```

**Describe the solution you'd like**
The `ci-images` image is probably more than we need for the VPA installer. We could try and find or build a more pared-down image that is windows-friendly.

**Describe alternatives you've considered**
* Not supporting Windows 🤷‍♂ 
* Fixing the mysterious issue with `ci-images`

**Comment by baderbuddy** [comment]
Just to add to this, but there's a good chance many of the other images used don't support Windows also.
