### ISSUE TITLE
[rbac-manager] Hard-coded runAsUser parameter is incompatible with Openshift 4

### ISSUE THREAD

**Issue by gswallow** [FairwindsOps/charts#270]
**Describe the bug**
I cannot install rbac-manager using the helm chart.  The deployment tries to start pods and fails:

> Error creating: pods "rbac-manager-78cbdd9fdb-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1200: must be in the ranges: [1000570000, 1000579999]]

**To Reproduce**
helm repo add fairwinds-stable https://charts.fairwinds.com/stable
helm install fairwinds-stable/rbac-manager --name rbac-manager --namespace rbac-manager
kubectl describe rs -n rbac-manager

**Expected behavior**
Pods would start up and run as any user in the acceptable range, or I would be instructed to create a service account and add it to a securityContextConstraint using `oc adm policy add-scc-to-user X`.

**Environment (please complete the following information):**
 - Helm Version: v3.1.1
 - Kubernetes Version v1.16.2 (Openshift 4.3.8)

**Comment by sudermanjr** [comment]
@gswallow Thanks for the report. We addressed this in the rbac-manager codebase and didn't update the chart. #271 addresses this.
