### ISSUE TITLE
Create HTML landing page for chart repository

### ISSUE THREAD

**Issue by davekonopka** [FairwindsOps/charts#30]
Create an HTML landing page for charts.reactiveops.com with details about the incubator and stable chart repos.

**Comment by sudermanjr** [comment]
I have reached out to marketing to provide the base page that I can add content to.

**Comment by sudermanjr** [comment]
Saw an example from jetstack where they just redirected to the helm hub page.  I really like this idea and I will work on that instead.

**Comment by davekonopka** [comment]
The redirect to Helm Hub is setup:
https://charts.reactiveops.com
