### ISSUE TITLE
[goldilocks] Make securityContext for pods configurable

### ISSUE THREAD

**Issue by usamaahmadkhan** [FairwindsOps/charts#313]
**Is your feature request related to a problem? Please describe.**
It is always good to have non-root/1000 user but in some cases (Openshift) the uid for certain applications in a namespace is restricted (e.g. user 11111-2222 can run containers in namespace `goldilocks-namespace`). In these scenarios the runAsUser needs to be configured for security purposes.

**Describe the solution you'd like**
If SecurityContext is not defined use the default, otherwise use what is specified.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rbren** [comment]
It'd be good to audit our use of `runAsUser` across all charts for this reason. `insights-agent` hard-codes them as well
