### ISSUE TITLE
[tests] Fail immediately if any chart fails the e2e tests

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/charts#343]
**Is your feature request related to a problem? Please describe.**
When I change multiple charts, and one of them fails, the tests still continue for each changed chart

**Describe the solution you'd like**
Fail immediately

**Describe alternatives you've considered**

**Additional context**
Most of our PRs are just one chart, so not a huge deal, but larger PRs are a pain to debug, as you have to scroll through heaps of CircleCI logs

**Comment by sudermanjr** [comment]
This is the repo we use https://github.com/helm/chart-testing/tree/master/ct/cmd

I don't see an option to fail fast or anything like that.
