### ISSUE TITLE
rbac-manager fails when image pulled from private repo

### ISSUE THREAD

**Issue by Jonito** [FairwindsOps/charts#346]
**Describe the bug**
getting error :getting Error: UPGRADE FAILED: error validating “”: error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field “imagePullSecrets” in io.k8s.api.core.v1.Container" when install from private (seen it in 1.5.4,1.5.5,1.5.6)

**To Reproduce**
any install of rbac-manager using private image repo

possible fix is the indentation of imagePullSecrets has to be in line with the container spec as shown here(https://kubernetes.io/docs/concepts/containers/images/).
https://github.com/FairwindsOps/charts/blob/8bdc696dcc8634b8fe3fd69f867c2d4d1f5858ab/stable/rbac-manager/templates/deployment.yaml#L38

**Comment by sudermanjr** [comment]
Thanks for the report! Looks like maybe that is from an old spec and we missed updating that.
