### ISSUE TITLE
Move the autospotting chart to charts repo

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/charts#36]
We have an autospotting chart floating around that should be moved to incubator.

**Comment by cristim** [comment]
@sudermanjr the author of AutoSpotting here, would you mind sharing this chart?

I'd like to link to it from our docs, considering how many people use AutoSpotting agsinst Kubernetes 
 infrastructure, there should be lots of people who would like to use this chart.

**Comment by cristim** [comment]
Sure, the software is licensed under the MIT license, you are free to do it.

Just the binaries that I build and actively support are proprietary, so that I can generate a small income to keep me motivated enough to work on it constantly.
