### ISSUE TITLE
[vpa] Allow specifying the image for the certgen container

### ISSUE THREAD

**Issue by matt-demers** [FairwindsOps/charts#390]
The image used for certgen is hardcoded into the chart (https://github.com/FairwindsOps/charts/blob/master/stable/vpa/templates/admission-controller-certgen.yaml#L64)

We try to pull all images for our cluster from a centralized repository, so we sync public images into one place. Since we cannot change the image for the certgen used in this chart we have to add a special rule to allow pulling it from the public repo. Please add a configuration option to the chart to override this image

**Comment by sudermanjr** [comment]
@matt-demers This makes a lot of sense. I opened #392 to fix.
