### ISSUE TITLE
[rbac-manager] Creation of CRDs should be optional

### ISSUE THREAD

**Issue by Jeinhaus** [FairwindsOps/charts#427]
**Is your feature request related to a problem? Please describe.**
The Helm documentation states, that [Helm 3 does not support upgrading CRDs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource).
Helm suggests either using the [special crds folder of Helm 3](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you) or [managing the CRDs outside the chart](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts).
In either case it would be great if the chart supported optional creation of the CRDs.

**Describe the solution you'd like**
Make the creation of CRDs optional (for backwards compatibility this could be enabled by default).
Also move the CRDs to the Helm3 `crds` folder so standard mechanisms like `helm install --skip-crds` work.

Would you accept a PR with these changes?

**Comment by sudermanjr** [comment]
I had to look and was surprised we never did this.

I think we would definitely accept a PR to move to the helm3 standard for this.

Thanks for bringing to this to our attention!

**Comment by Jeinhaus** [comment]
Could you have a look at the PR? I'm not sure if this required bumping the Chart's major version @sudermanjr
