### ISSUE TITLE
fairwinds-stable/vpa - no admission controller is getting deployed

### ISSUE THREAD

**Issue by Richardmbs12** [FairwindsOps/charts#540]
**Describe the bug**
When installing this helm chart, no admission controller deployment is registered

**To Reproduce**
helm repo add fairwinds-stable https://charts.fairwinds.com/stable
helm install vpa fairwinds-stable/vpa --namespace vpa --create-namespace

(I have tried both 0.4.1 and 0.4.2)

**Expected behavior**
The admission controller should be deployed

**Comment by Richardmbs12** [comment]
I see I had to explicity set the helm chart value admissionController.enabled to true as its defaulted to false
So I see this isnt per say a bug, just not what I expected from the chart setting

Shouldnt this rather be set to true as vpa requires the admission controller by default?

**Comment by sudermanjr** [comment]
We only typically use VPA in recommendation mode which does not require the admission controller. 

That's why the defaults on this chart are set like that

**Comment by japneet23** [comment]
Hello @sudermanjr

Is there a way we can retain VPA recommendation data for a longer time? I want to know if there is any way to do this other than using Prometheus. Currently, the retention is for 30 minutes, I guess.
