### ISSUE TITLE
New Configuration Type for Cert-Manager

### ISSUE THREAD

**Issue by endzyme** [FairwindsOps/charts#91]
https://github.com/jetstack/cert-manager/commit/f82a1cf5b3d0fabd38974ab31c5d31d61c57a235#diff-8fe9226f0eaa914b2b08a08269010a27

Cert manager setup chart will need some love at some point to use this new `solver: []` configuration.

**Comment by ivanfetch** [comment]
This is still relevant

**Comment by sudermanjr** [comment]
This has become more urgent due to LE not supporting versions before 0.8.0 soon.

**Comment by lucasreed** [comment]
Yep, this can be closed I think.
> @lucasreed this is fixed by your new letsencrypt-setup chart, correct?
