### ISSUE TITLE
incubator/ro-cert-manager race condition with cert-manager chart

### ISSUE THREAD

**Issue by ivanfetch** [FairwindsOps/charts#97]
When this chart is installed too quickly after versions 0.6+ of the cert-manager chart, the cert-manager validating webhook may not yet be initialized, making cert-manager incapable of creating its Clusterissuer objects.

The current work-around is:

* Set the `cert-manager.enabled` value to `false` for this chart
* Install the cert-manager chart separately.
* Verify that cert-manager is capable of creating ClusterIssuer objects, instead of returning an error that the validating webhook can not satisfy the request.
* Install this chart.

A potential solution is using a Helm pre-install hook to create a Kubernetes job that wil run a shell loop to verify ClusterIssuer objects can be created by cert-manager, before this chart attempts to create them.

**Comment by sudermanjr** [comment]
I'm going to go ahead and close this.  We aren't going to continue installing cert-manager with the ro-cert-manager chart going forward due to large changes in cert-manager lately.
